name: content-bin-consumer
version: "1.0"
summary: The 'content-bin-consumer' snap
description: |
    This is a simple snap example showing how to share content
grade: stable
confinement: strict

apps:
 echo:
   command: bin/echo_consumer

plugs:
  content1:
    interface: content
    content: executables
    target: $SNAP/extra-bin

parts:
 hello:
  plugin: dump
  source: .
  install: |
    # Create directory to serve as mount point for extra-bin
    mkdir -p $SNAPCRAFT_PART_INSTALL/extra-bin
