name: content-bin-producer
version: "1.0"
summary: The 'content-bin-producer' snap
description: |
    This is a simple snap example showing how to share content

grade: stable
confinement: strict

slots:
  content1:
    interface: content
    content: executables
    read: 
      - $SNAP/bin

parts:
 hello:
  plugin: dump
  source: .
